CREATE DATABASE IF NOT EXISTS ecole_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ecole_app;

CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(80) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('ADMIN','DIRECTION','SECRETARIAT','CAISSE','ENSEIGNANT','PEDAGOGIE','PARENT') NOT NULL DEFAULT 'SECRETARIAT',
 nom_complet VARCHAR(150) NOT NULL,
 actif TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS etablissements (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(180) NOT NULL,
 adresse VARCHAR(255), telephone VARCHAR(50), email VARCHAR(120),
 actif TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS annees_scolaires (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 libelle VARCHAR(30) NOT NULL UNIQUE,
 date_debut DATE, date_fin DATE, active TINYINT(1) DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS niveaux (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(100) NOT NULL, actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sections (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(100) NOT NULL, actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS options (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(120) NOT NULL, actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS classes (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(100) NOT NULL,
 niveau_id INT UNSIGNED NULL, section_id INT UNSIGNED NULL, option_id INT UNSIGNED NULL,
 salle VARCHAR(80), actif TINYINT(1) DEFAULT 1,
 FOREIGN KEY(niveau_id) REFERENCES niveaux(id) ON DELETE SET NULL,
 FOREIGN KEY(section_id) REFERENCES sections(id) ON DELETE SET NULL,
 FOREIGN KEY(option_id) REFERENCES options(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS eleves (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matricule VARCHAR(50) NOT NULL UNIQUE,
 nom VARCHAR(100) NOT NULL, postnom VARCHAR(100), prenom VARCHAR(100),
 sexe ENUM('M','F','AUTRE') DEFAULT 'M', date_naissance DATE NULL,
 lieu_naissance VARCHAR(120), adresse VARCHAR(255), telephone VARCHAR(50),
 photo VARCHAR(255), actif TINYINT(1) DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS parents (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom_complet VARCHAR(180) NOT NULL, telephone VARCHAR(50), email VARCHAR(120), adresse VARCHAR(255), profession VARCHAR(120)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS eleve_parents (
 eleve_id INT UNSIGNED NOT NULL, parent_id INT UNSIGNED NOT NULL,
 lien VARCHAR(60), principal TINYINT(1) DEFAULT 0,
 PRIMARY KEY(eleve_id,parent_id),
 FOREIGN KEY(eleve_id) REFERENCES eleves(id) ON DELETE CASCADE,
 FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inscriptions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 eleve_id INT UNSIGNED NOT NULL, annee_scolaire_id INT UNSIGNED NOT NULL, classe_id INT UNSIGNED NOT NULL,
 date_inscription DATE NOT NULL, statut ENUM('active','terminee','annulee','transferee') DEFAULT 'active',
 FOREIGN KEY(eleve_id) REFERENCES eleves(id),
 FOREIGN KEY(annee_scolaire_id) REFERENCES annees_scolaires(id),
 FOREIGN KEY(classe_id) REFERENCES classes(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS enseignants (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matricule VARCHAR(50) UNIQUE, nom_complet VARCHAR(180) NOT NULL,
 telephone VARCHAR(50), email VARCHAR(120), specialite VARCHAR(120), actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS personnel (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matricule VARCHAR(50) UNIQUE, nom_complet VARCHAR(180) NOT NULL,
 fonction VARCHAR(120), telephone VARCHAR(50), actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS matieres (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(30) UNIQUE, nom VARCHAR(120) NOT NULL, coefficient DECIMAL(5,2) DEFAULT 1, actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS affectations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 enseignant_id INT UNSIGNED NOT NULL, matiere_id INT UNSIGNED NOT NULL, classe_id INT UNSIGNED NOT NULL,
 FOREIGN KEY(enseignant_id) REFERENCES enseignants(id) ON DELETE CASCADE,
 FOREIGN KEY(matiere_id) REFERENCES matieres(id) ON DELETE CASCADE,
 FOREIGN KEY(classe_id) REFERENCES classes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS presences_eleves (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 eleve_id INT UNSIGNED NOT NULL, date_presence DATE NOT NULL,
 statut ENUM('present','absent','retard','justifie') NOT NULL,
 motif VARCHAR(255), UNIQUE KEY uq_presence(eleve_id,date_presence),
 FOREIGN KEY(eleve_id) REFERENCES eleves(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS presences_enseignants (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 enseignant_id INT UNSIGNED NOT NULL, date_presence DATE NOT NULL,
 statut ENUM('present','absent','retard','justifie') NOT NULL,
 motif VARCHAR(255), UNIQUE KEY uq_presence_ens(enseignant_id,date_presence),
 FOREIGN KEY(enseignant_id) REFERENCES enseignants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS periodes (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 annee_scolaire_id INT UNSIGNED NOT NULL, nom VARCHAR(80) NOT NULL,
 FOREIGN KEY(annee_scolaire_id) REFERENCES annees_scolaires(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS evaluations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matiere_id INT UNSIGNED NOT NULL, classe_id INT UNSIGNED NOT NULL, periode_id INT UNSIGNED NOT NULL,
 libelle VARCHAR(120) NOT NULL, date_evaluation DATE,
 FOREIGN KEY(matiere_id) REFERENCES matieres(id),
 FOREIGN KEY(classe_id) REFERENCES classes(id),
 FOREIGN KEY(periode_id) REFERENCES periodes(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 evaluation_id INT UNSIGNED NOT NULL, eleve_id INT UNSIGNED NOT NULL,
 note DECIMAL(6,2) NOT NULL, appreciation VARCHAR(255),
 UNIQUE KEY uq_note(evaluation_id,eleve_id),
 FOREIGN KEY(evaluation_id) REFERENCES evaluations(id) ON DELETE CASCADE,
 FOREIGN KEY(eleve_id) REFERENCES eleves(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS types_frais (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nom VARCHAR(120) NOT NULL, description VARCHAR(255), actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS frais_scolaires (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 eleve_id INT UNSIGNED NOT NULL, type_frais_id INT UNSIGNED NOT NULL, annee_scolaire_id INT UNSIGNED NOT NULL,
 montant_du DECIMAL(14,2) NOT NULL DEFAULT 0,
 FOREIGN KEY(eleve_id) REFERENCES eleves(id), FOREIGN KEY(type_frais_id) REFERENCES types_frais(id),
 FOREIGN KEY(annee_scolaire_id) REFERENCES annees_scolaires(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paiements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 eleve_id INT UNSIGNED NOT NULL, frais_id BIGINT UNSIGNED NULL,
 montant DECIMAL(14,2) NOT NULL, mode_paiement ENUM('especes','mobile_money','banque','autre') DEFAULT 'especes',
 reference_paiement VARCHAR(100), date_paiement DATETIME DEFAULT CURRENT_TIMESTAMP,
 statut ENUM('valide','annule') DEFAULT 'valide',
 FOREIGN KEY(eleve_id) REFERENCES eleves(id), FOREIGN KEY(frais_id) REFERENCES frais_scolaires(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 eleve_id INT UNSIGNED NULL, nom VARCHAR(180) NOT NULL, fichier VARCHAR(255) NOT NULL,
 type_document VARCHAR(80), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(eleve_id) REFERENCES eleves(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS journal_activites (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NULL, action VARCHAR(120) NOT NULL, module VARCHAR(80),
 details TEXT, ip_address VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

INSERT INTO users(username,password_hash,role,nom_complet)
SELECT 'admin', '$2y$12$KgnkdlXbO3HdlZV2ECMhreYUXQ8g6KHuNTqlgKVVKjZ.7L2E1..hW', 'ADMIN', 'Administrateur'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='admin');

INSERT INTO etablissements(nom) SELECT 'Mon établissement scolaire' WHERE NOT EXISTS (SELECT 1 FROM etablissements LIMIT 1);
INSERT INTO annees_scolaires(libelle,active) SELECT '2026-2027',1 WHERE NOT EXISTS (SELECT 1 FROM annees_scolaires WHERE active=1);
