let session=null,current='dashboard',cache={};
const roles=['ADMIN','DIRECTION','SECRETARIAT','CAISSE','ENSEIGNANT','PEDAGOGIE'];
const nav=[['dashboard','🏠','Tableau de bord'],['students','👨‍🎓','Élèves'],['teachers','👩‍🏫','Enseignants'],['classes','🏫','Classes'],['payments','💰','Paiements'],['attendance','📋','Présences'],['users','👤','Utilisateurs'],['security','🔐','Mon code']];
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function can(m){if(session.role==='ADMIN')return true;if(session.role==='CAISSE')return ['dashboard','payments'].includes(m);if(session.role==='ENSEIGNANT')return ['dashboard','students','classes','teachers','attendance','security'].includes(m);if(session.role==='PEDAGOGIE')return ['dashboard','students','teachers','classes','attendance','security'].includes(m);if(session.role==='SECRETARIAT')return ['dashboard','students','teachers','classes','security'].includes(m);if(session.role==='DIRECTION')return m!=='users';return m==='dashboard'||m==='security';}
function login(){document.getElementById('app').innerHTML='<div class="login"><div class="box"><div class="logo">🎓 Ecole-App-1</div><div class="muted">Gestion scolaire — version Windows</div><div class="field"><label>Identifiant</label><input id="u" value="admin" autocomplete="username"></div><div class="field"><label>Code personnel</label><input id="p" type="password" placeholder="Code"></div><div id="msg"></div><button class="btn primary" style="width:100%" onclick="doLogin()">Se connecter</button><p class="muted" style="font-size:12px;margin-top:16px">Première connexion administrateur : code 1234. Changez-le immédiatement.</p></div></div>'}
async function doLogin(){const r=await window.api.login({username:document.getElementById('u').value,code:document.getElementById('p').value});if(!r.ok){document.getElementById('msg').innerHTML='<p class="error">'+esc(r.message)+'</p>';return}session=r.user;if(session.mustChangeCode){changeCode(true);return}render()}
function logout(){session=null;login()}
async function load(t){cache[t]=await window.api.list(t);return cache[t]}
async function render(){if(!session)return login();let visible=nav.filter(x=>can(x[0]));document.getElementById('app').innerHTML='<div class="layout"><aside class="side"><div class="brand">🎓 <span>Ecole-App-1</span></div><nav class="nav">'+visible.map(n=>'<button class="'+(current===n[0]?'active':'')+'" onclick="go(\''+n[0]+'\')">'+n[0]+' '+n[1]+' '+n[2]+'</button>').join('')+'</nav><div style="margin-top:25px;padding:12px;font-size:13px;color:#b9c9e8">Connecté : <b>'+esc(session.username)+'</b><br>Rôle : '+esc(session.role)+'</div><button class="btn danger" style="margin:12px" onclick="logout()">Déconnexion</button></aside><main class="main"><div class="top"><div><h1>'+nav.find(x=>x[0]===current)?.[2]+'</h1><div class="muted">Données locales SQLite persistantes</div></div><div class="actions"><button class="btn secondary" onclick="backup()">Sauvegarder</button><button class="btn secondary" onclick="restore()">Restaurer</button></div></div>'+await content()+'</main></div>'}
async function go(x){current=x;render()}
async function content(){if(current==='dashboard'){let [a,b,c,d,e]=await Promise.all(['students','teachers','classes','payments','attendance'].map(load));return '<div class="grid">'+stat('Élèves',a.length,'students')+stat('Enseignants',b.length,'teachers')+stat('Classes',c.length,'classes')+stat('Paiements',d.length,'payments')+'</div><div class="card" style="margin-top:16px"><h3>Stockage permanent</h3><p class="muted">La base SQLite est conservée dans Documents/Ecole-App-1/data. Les sauvegardes sont placées dans Documents/Ecole-App-1/sauvegardes.</p><p><b>Utilisateur :</b> '+esc(session.username)+' — <b>Rôle :</b> '+esc(session.role)+'</p></div>'}
if(current==='users')return usersView();
if(current==='security')return '<div class="card"><h3>Modifier mon code personnel</h3><div class="field"><label>Ancien code</label><input id="oldc" type="password"></div><div class="field"><label>Nouveau code</label><input id="newc" type="password"></div><button class="btn primary" onclick="saveCode()">Modifier</button></div>';
const map={students:['Élèves',['Nom','Sexe','Classe','Téléphone']],teachers:['Enseignants',['Nom','Matière','Téléphone']],classes:['Classes',['Nom']],payments:['Paiements',['Élève','Montant','Type','Date']],attendance:['Présences',['Élève','Date','Statut']]};return tableView(map[current][0],map[current][1],await load(current),current)}
function stat(a,b,c){return '<div class="card stat"><div class="muted">'+a+'</div><b>'+b+'</b><button class="btn secondary" onclick="go(\''+c+'\')">Ouvrir</button></div>'}
function tableView(title,heads,arr,type){const fields={students:['name','sex','class','phone'],teachers:['name','subject','phone'],classes:['name'],payments:['student','amount','type','date'],attendance:['student','date','status']}[type];return '<div class="card"><div class="toolbar"><b>'+title+' ('+arr.length+')</b><button class="btn primary" onclick="addForm(\''+type+'\')">+ Ajouter</button></div>'+(arr.length?'<div class="table-wrap"><table class="table"><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'<th>Action</th></tr>'+arr.map(o=>'<tr>'+fields.map(f=>'<td>'+esc(o[f])+'</td>').join('')+'<td><button class="btn danger" onclick="delRow(\''+type+'\','+o.id+')">Supprimer</button></td></tr>').join('')+'</table></div>':'<div class="muted">Aucune donnée.</div>')+'</div>'}
function addForm(type){const defs={students:[['name','Nom complet'],['sex','Sexe'],['class','Classe'],['phone','Téléphone']],teachers:[['name','Nom complet'],['subject','Matière'],['phone','Téléphone']],classes:[['name','Nom de classe']],payments:[['student','Élève'],['amount','Montant FC'],['type','Type de frais'],['date','Date']],attendance:[['student','Élève'],['date','Date'],['status','Statut']]};const f=defs[type];document.body.insertAdjacentHTML('beforeend','<div class="modal"><div class="card"><h2>Ajouter</h2><div class="form-grid">'+f.map(x=>'<div class="field"><label>'+x[1]+'</label><input id="f_'+x[0]+'"></div>').join('')+'</div><button class="btn secondary" onclick="this.closest(\'.modal\').remove()">Annuler</button> <button class="btn primary" onclick="submitForm(\''+type+'\')">Enregistrer</button></div></div>')}
async function submitForm(type){const keys={students:['name','sex','class','phone'],teachers:['name','subject','phone'],classes:['name'],payments:['student','amount','type','date'],attendance:['student','date','status']}[type];const values={};keys.forEach(k=>values[k]=document.getElementById('f_'+k).value);if(keys.some(k=>!values[k]))return alert('Veuillez remplir tous les champs.');await window.api.add({table:type,values});document.querySelector('.modal').remove();render()}
async function delRow(table,id){if(confirm('Supprimer cette donnée ?')){await window.api.remove({table,id});render()}}
function usersView(){return '<div class="card"><div class="toolbar"><b>Utilisateurs</b><button class="btn primary" onclick="userForm()">+ Nouvel utilisateur</button></div><div class="table-wrap"><table class="table"><tr><th>Identifiant</th><th>Rôle</th><th>Statut</th><th>Actions</th></tr>'+ (cache.users||[]).map(u=>'<tr><td>'+esc(u.username)+'</td><td><span class="badge">'+esc(u.role)+'</span></td><td>'+esc(u.status)+'</td><td class="actions"><button class="btn secondary" onclick="resetUser('+u.id+')">Réinitialiser code</button><button class="btn '+(u.status==='ACTIVE'?'danger':'success')+'" onclick="toggleUser('+u.id+',\''+u.status+'\')">'+(u.status==='ACTIVE'?'Désactiver':'Activer')+'</button></td></tr>').join('')+'</table></div></div>'}
async function userForm(){document.body.insertAdjacentHTML('beforeend','<div class="modal"><div class="card"><h2>Créer un utilisateur</h2><div class="field"><label>Identifiant</label><input id="nu"></div><div class="field"><label>Code personnel</label><input id="nc" type="password"></div><div class="field"><label>Rôle</label><select id="nr">'+roles.filter(x=>x!=='ADMIN').map(x=>'<option>'+x+'</option>').join('')+'</select></div><button class="btn secondary" onclick="this.closest(\'.modal\').remove()">Annuler</button> <button class="btn primary" onclick="createUser()">Créer</button></div></div>')}
async function createUser(){const r=await window.api.createUser({username:nu.value,code:nc.value,role:nr.value});if(!r.ok)return alert(r.message);document.querySelector('.modal').remove();render()}
async function toggleUser(id,status){await window.api.setUserStatus({id,status:status==='ACTIVE'?'INACTIVE':'ACTIVE'});render()}
async function resetUser(id){const code=prompt('Nouveau code (minimum 4 caractères)');if(code){const r=await window.api.resetCode({id,code});if(!r.ok)alert(r.message);render()}}
function changeCode(force=false){document.getElementById('app').innerHTML='<div class="login"><div class="box"><div class="logo">🔐 '+(force?'Changement obligatoire':'Modifier mon code')+'</div><p class="muted">Pour sécuriser votre compte, définissez votre code personnel.</p><div class="field"><label>Ancien code</label><input id="oldc" type="password"></div><div class="field"><label>Nouveau code</label><input id="newc" type="password"></div><div id="msg"></div><button class="btn primary" style="width:100%" onclick="saveCode('+force+')">Enregistrer</button></div></div>'}
async function saveCode(force=false){const r=await window.api.changeCode({userId:session.id,oldCode:document.getElementById('oldc').value,newCode:document.getElementById('newc').value});if(!r.ok){document.getElementById('msg').innerHTML='<p class="error">'+esc(r.message)+'</p>';return}session.mustChangeCode=false;force?render():alert('Code modifié avec succès.')}
async function backup(){const r=await window.api.backup();if(r.ok)alert('Sauvegarde créée :\\n'+r.path)}
async function restore(){if(confirm('Restaurer une sauvegarde remplacera les données actuelles. Continuer ?')){const r=await window.api.restore();if(r.ok){alert('Restauration terminée.');render()}else if(r.message)alert(r.message)}}
(async()=>{login()})()
