let session=null,current='dashboard',cache={};
const nav=[['dashboard','🏠','Tableau de bord'],['students','🎓','Élèves'],['parents','👨‍👩‍👧','Parents'],['enrollments','📝','Inscriptions'],['teachers','👩‍🏫','Enseignants'],['staff','👥','Personnel'],['classes','🏫','Classes'],['subjects','📚','Matières'],['assignments','🔗','Affectations'],['schedules','🕒','Horaires'],['student_attendance','📋','Présences élèves'],['teacher_attendance','🧑‍🏫','Présences enseignants'],['periods','📅','Périodes'],['evaluations','📝','Évaluations'],['grades','📊','Notes'],['academic_years','📆','Années scolaires'],['fee_types','💰','Frais scolaires'],['student_fees','💳','Dettes / soldes'],['payments','🧾','Paiements'],['documents','📄','Documents'],['reports','📈','Rapports'],['users','🔐','Utilisateurs'],['security','⚙️','Mon code']];
const roles=['ADMIN','DIRECTION','SECRETARIAT','CAISSE','ENSEIGNANT','PEDAGOGIE'];
const cfg={
students:{title:'Élèves',fields:[['matricule','Matricule','text'],['name','Nom','text',1],['postname','Postnom','text'],['firstname','Prénom','text'],['sex','Sexe','select',['M','F']],['birth_date','Date naissance','date'],['birth_place','Lieu naissance','text'],['nationality','Nationalité','text'],['address','Adresse','text'],['phone','Téléphone','text'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']]]},
parents:{title:'Parents',fields:[['name','Nom complet','text',1],['phone','Téléphone','text'],['email','Email','email'],['address','Adresse','text'],['occupation','Profession','text']]},
enrollments:{title:'Inscriptions',fields:[['student_id','Élève','ref','students'],['year_id','Année','ref','academic_years'],['class_id','Classe','ref','classes'],['enroll_date','Date','date'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']],['old_school','Ancien établissement','text'],['file_number','N° dossier','text'],['observation','Observation','text']]},
teachers:{title:'Enseignants',fields:[['matricule','Matricule','text'],['name','Nom complet','text',1],['subject','Matière principale','text'],['phone','Téléphone','text'],['email','Email','email'],['address','Adresse','text'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']]]},
staff:{title:'Personnel',fields:[['name','Nom complet','text',1],['job','Fonction','text'],['phone','Téléphone','text'],['email','Email','email'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']]]},
classes:{title:'Classes',fields:[['name','Nom de classe','text',1],['level_id','Niveau','ref','levels'],['section_id','Section','ref','sections'],['option_id','Option','ref','options'],['room_id','Salle','ref','rooms'],['year_id','Année','ref','academic_years'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']]]},
levels:{title:'Niveaux',fields:[['name','Nom','text',1]]},sections:{title:'Sections',fields:[['name','Nom','text',1]]},options:{title:'Options',fields:[['name','Nom','text',1]]},rooms:{title:'Salles',fields:[['name','Nom','text',1]]},
subjects:{title:'Matières',fields:[['code','Code','text'],['name','Nom','text',1],['coefficient','Coefficient','number'],['level','Niveau','text'],['volume_hours','Volume horaire','number'],['description','Description','text']]},
assignments:{title:'Affectations',fields:[['teacher_id','Enseignant','ref','teachers'],['subject_id','Matière','ref','subjects'],['class_id','Classe','ref','classes'],['year_id','Année','ref','academic_years'],['status','Statut','select',['ACTIVE','INACTIVE','ARCHIVED']]]},
schedules:{title:'Horaires',fields:[['class_id','Classe','ref','classes'],['teacher_id','Enseignant','ref','teachers'],['subject_id','Matière','ref','subjects'],['room_id','Salle','ref','rooms'],['day','Jour','select',['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi']],['start_time','Début','time'],['end_time','Fin','time']]},
student_attendance:{title:'Présences élèves',fields:[['student_id','Élève','ref','students'],['class_id','Classe','ref','classes'],['date','Date','date'],['time','Heure','time'],['status','Statut','select',['PRESENT','ABSENT','RETARD','JUSTIFIE','NON_JUSTIFIE']],['motif','Motif','text'],['observation','Observation','text']]},
teacher_attendance:{title:'Présences enseignants',fields:[['teacher_id','Enseignant','ref','teachers'],['date','Date','date'],['time','Heure','time'],['status','Statut','select',['PRESENT','ABSENT','RETARD']],['motif','Motif','text']]},
periods:{title:'Périodes',fields:[['name','Nom','text',1],['year_id','Année','ref','academic_years'],['start_date','Début','date'],['end_date','Fin','date'],['status','Statut','select',['OPEN','CLOSED']]]},
evaluations:{title:'Évaluations',fields:[['name','Nom','text',1],['type','Type','select',['INTERROGATION','DEVOIR','CONTROLE','EXAMEN','TRIMESTRIEL','SEMESTRIEL']],['subject_id','Matière','ref','subjects'],['class_id','Classe','ref','classes'],['period_id','Période','ref','periods'],['date','Date','date'],['max_score','Maximum','number'],['coefficient','Coefficient','number']]},
grades:{title:'Notes',fields:[['student_id','Élève','ref','students'],['evaluation_id','Évaluation','ref','evaluations'],['score','Note','number'],['appreciation','Appréciation','text']]},
academic_years:{title:'Années scolaires',fields:[['label','Année','text',1],['status','Statut','select',['OPEN','ACTIVE','CLOSED','ARCHIVED']]]},
fee_types:{title:'Types de frais',fields:[['name','Frais','text',1],['amount','Montant','number'],['year_id','Année','ref','academic_years'],['due_date','Échéance','date'],['status','Statut','select',['ACTIVE','INACTIVE']]]},
student_fees:{title:'Frais attribués / Dettes',fields:[['student_id','Élève','ref','students'],['fee_type_id','Frais','ref','fee_types'],['amount_due','Montant dû','number'],['discount','Réduction','number'],['due_date','Échéance','date'],['status','Statut','select',['OPEN','PARTIAL','PAID','OVERDUE']]]},
payments:{title:'Paiements / Reçus',fields:[['student_id','Élève','ref','students'],['fee_type_id','Frais','ref','fee_types'],['amount','Montant','number',1],['date','Date','date'],['receipt_no','N° reçu','text'],['method','Mode','select',['ESPECES','BANQUE','MOBILE_MONEY','AUTRE']],['cashier','Caissier','text'],['observation','Observation','text']]},
documents:{title:'Documents',fields:[['student_id','Élève','ref','students'],['type','Type','select',['ATTESTATION_INSCRIPTION','CERTIFICAT_SCOLARITE','ATTESTATION_FREQUENTATION','RELEVE_NOTES','BULLETIN','CERTIFICAT_REUSSITE','CERTIFICAT_TRANSFERT','AUTRE']],['title','Titre','text',1],['file_path','Fichier / chemin','text']]}
};
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]});}
function can(m){if(session.role==='ADMIN')return true;var p={DIRECTION:['dashboard','students','parents','enrollments','teachers','staff','classes','subjects','assignments','schedules','student_attendance','teacher_attendance','periods','evaluations','grades','academic_years','fee_types','student_fees','payments','documents','reports','security'],SECRETARIAT:['dashboard','students','parents','enrollments','teachers','staff','classes','documents','reports','security'],CAISSE:['dashboard','students','student_fees','fee_types','payments','reports','security'],ENSEIGNANT:['dashboard','students','classes','subjects','schedules','student_attendance','evaluations','grades','reports','security'],PEDAGOGIE:['dashboard','students','classes','subjects','assignments','schedules','student_attendance','evaluations','grades','reports','security']};return (p[session.role]||['dashboard','security']).indexOf(m)>=0;}
function login(){document.getElementById('app').innerHTML='<div class="login"><div class="login-box"><div class="brand-big">🎓 <span>Ecole-App-1</span></div><h2>Gestion scolaire intégrée</h2><p class="muted">Windows • Hors ligne • SQLite permanent</p><div class="field"><label>Identifiant</label><input id="u" value="admin"></div><div class="field"><label>Code personnel</label><input id="p" type="password" onkeydown="if(event.key===\\'Enter\\')doLogin()"></div><div id="msg"></div><button class="btn primary full" onclick="doLogin()">Se connecter</button><div class="hint">Première connexion : <b>admin / 1234</b>. Changement obligatoire.</div></div></div>';}
async function doLogin(){try{var r=await window.api.login({username:document.getElementById('u').value,code:document.getElementById('p').value});if(!r.ok){document.getElementById('msg').innerHTML='<div class="error">'+esc(r.message)+'</div>';return;}session=r.user;if(session.mustChangeCode){changeCode(true);return;}render();}catch(e){document.getElementById('msg').innerHTML='<div class="error">'+esc(e.message)+'</div>';}}
function logout(){session=null;cache={};current='dashboard';login();}
function go(x){current=x;render();}
async function load(t,s){cache[t]=await window.api.list({table:t,search:s||''});return cache[t];}
async function content(){if(current==='dashboard')return dashboard();if(current==='reports')return reports();if(current==='users')return usersView();if(current==='security')return security();return moduleView(current);}
async function render(){if(!session)return login();var n=nav.filter(function(x){return can(x[0])});var h='<div class="layout"><aside class="side"><div class="brand">🎓 <span>Ecole-App-1</span></div><div class="side-version">Gestion scolaire intégrée</div><nav>';n.forEach(function(x){h+='<button class="'+(current===x[0]?'active':'')+'" onclick="go(\\''+x[0]+'\\')">'+x[1]+' <span>'+x[2]+'</span></button>';});h+='</nav><div class="user-card"><b>'+esc(session.username)+'</b><br><span>'+esc(session.role)+'</span></div><button class="btn danger full" onclick="logout()">Déconnexion</button></aside><main class="main"><header class="topbar"><div><h1>'+title()+'</h1><div class="muted">Base locale SQLite • fonctionnement sans Internet</div></div><div class="top-actions"><button class="btn secondary" onclick="backup()">Sauvegarde</button><button class="btn secondary" onclick="restore()">Restaurer</button></div></header><section class="page">'+await content()+'</section></main></div>';document.getElementById('app').innerHTML=h;}
function title(){var x=nav.find(function(n){return n[0]===current});return x?x[2]:'Tableau de bord';}
async function dashboard(){var d=await window.api.dashboard();return '<div class="cards">'+stat('Élèves',d.students,'students','🎓')+stat('Enseignants',d.teachers,'teachers','👩‍🏫')+stat('Classes',d.classes,'classes','🏫')+stat('Paiements',d.payments,'payments','💰')+stat('Recettes',d.revenue.toLocaleString(),'payments','🧾')+stat('Présence',d.presenceRate+' %','student_attendance','📋')+'</div><div class="grid2"><div class="card"><h3>Base de données</h3><p>SQLite permanent, sauvegarde locale et restauration intégrées.</p><button class="btn primary" onclick="showInfo()">Voir l’emplacement</button></div><div class="card"><h3>Accès rapide</h3><div class="quick">'+nav.filter(function(x){return can(x[0])&&x[0]!=='dashboard'}).slice(0,8).map(function(x){return '<button class="quick-btn" onclick="go(\\''+x[0]+'\\')">'+x[1]+' '+x[2]+'</button>'}).join('')+'</div></div></div>';}
function stat(a,b,c,i){return '<div class="stat card"><div class="stat-icon">'+i+'</div><div><div class="muted">'+a+'</div><b>'+esc(b)+'</b></div><button class="btn link" onclick="go(\\''+c+'\\')">Ouvrir →</button></div>';}
async function moduleView(type){var c=cfg[type];if(!c)return '<div class="card">Module indisponible.</div>';var s=cache['_s_'+type]||'',rows=await load(type,s);var h='<div class="card"><div class="toolbar"><div><b>'+c.title+'</b><span class="count">'+rows.length+'</span></div><div class="toolbar-actions"><input class="search" placeholder="Rechercher…" value="'+esc(s)+'" oninput="searchM(\\''+type+'\\',this.value)"><button class="btn primary" onclick="addForm(\\''+type+'\\')">+ Ajouter</button><button class="btn secondary" onclick="exportCsv(\\''+type+'\\')">CSV</button></div></div>';if(!rows.length)return h+'<div class="empty">Aucune donnée.</div></div>';h+='<div class="table-wrap"><table><thead><tr>';c.fields.forEach(function(f){h+='<th>'+f[1]+'</th>';});h+='<th>Action</th></tr></thead><tbody>';rows.forEach(function(r){h+='<tr>';c.fields.forEach(function(f){h+='<td>'+esc(r[f[0]])+'</td>';});h+='<td><button class="btn danger small" onclick="delRow(\\''+type+'\\','+r.id+')">Archiver</button></td></tr>';});return h+'</tbody></table></div></div>';}
function searchM(t,v){cache['_s_'+t]=v;clearTimeout(window._tm);window._tm=setTimeout(render,250);}
async function addForm(type){var c=cfg[type],html='<div class="modal"><div class="modal-box"><h2>'+c.title+' — Ajouter</h2><div class="form-grid">';for(var i=0;i<c.fields.length;i++){var f=c.fields[i];html+='<div class="field"><label>'+f[1]+(f[3]===1?' *':'')+'</label>';if(f[2]==='ref'){var os=await window.api.options(f[3]);html+='<select id="f_'+f[0]+'"><option value="">-- Choisir --</option>';os.forEach(function(o){html+='<option value="'+o.id+'">'+esc(o.label)+'</option>';});html+='</select>';}else if(f[2]==='select'){html+='<select id="f_'+f[0]+'"><option value="">-- Choisir --</option>'+f[3].map(function(o){return '<option>'+o+'</option>'}).join('')+'</select>';}else html+='<input id="f_'+f[0]+'" type="'+(f[2]||'text')+'">';html+='</div>';}html+='</div><div class="modal-actions"><button class="btn secondary" onclick="this.closest(\\'.modal\\').remove()">Annuler</button><button class="btn primary" onclick="submitForm(\\''+type+'\\')">Enregistrer</button></div></div></div>';document.body.insertAdjacentHTML('beforeend',html);}
async function submitForm(type){var c=cfg[type],v={};c.fields.forEach(function(f){v[f[0]]=document.getElementById('f_'+f[0]).value;});for(var i=0;i<c.fields.length;i++)if(c.fields[i][3]===1&&!v[c.fields[i][0]])return alert('Champ obligatoire : '+c.fields[i][1]);try{await window.api.add({table:type,values:v});document.querySelector('.modal').remove();render();}catch(e){alert('Erreur : '+e.message);}}
async function delRow(t,id){if(confirm('Archiver cette donnée ?')){try{await window.api.remove({table:t,id:id});render();}catch(e){alert(e.message);}}}
async function exportCsv(t){var r=await window.api.exportCsv({table:t,search:cache['_s_'+t]||''});if(r.ok)alert('Export créé :\\n'+r.path);}
async function usersView(){var us=await window.api.users();var h='<div class="card"><div class="toolbar"><b>Utilisateurs ('+us.length+')</b><button class="btn primary" onclick="userForm()">+ Nouvel utilisateur</button></div><div class="table-wrap"><table><tr><th>Identifiant</th><th>Rôle</th><th>Statut</th><th>Changement code</th><th>Actions</th></tr>';us.forEach(function(u){h+='<tr><td>'+esc(u.username)+'</td><td><span class="badge">'+esc(u.role)+'</span></td><td>'+esc(u.status)+'</td><td>'+(u.must_change_code?'Oui':'Non')+'</td><td><button class="btn secondary small" onclick="resetUser('+u.id+')">Réinitialiser</button> <button class="btn danger small" onclick="toggleUser('+u.id+',\\''+u.status+'\\')">Activer/Désactiver</button></td></tr>';});return h+'</table></div></div>';}
function userForm(){document.body.insertAdjacentHTML('beforeend','<div class="modal"><div class="modal-box"><h2>Créer un utilisateur</h2><div class="field"><label>Identifiant</label><input id="nu"></div><div class="field"><label>Code</label><input id="nc" type="password"></div><div class="field"><label>Rôle</label><select id="nr">'+roles.filter(function(x){return x!=='ADMIN'}).map(function(x){return '<option>'+x+'</option>'}).join('')+'</select></div><div class="modal-actions"><button class="btn secondary" onclick="this.closest(\\'.modal\\').remove()">Annuler</button><button class="btn primary" onclick="createUser()">Créer</button></div></div></div>');}
async function createUser(){var r=await window.api.createUser({username:document.getElementById('nu').value,code:document.getElementById('nc').value,role:document.getElementById('nr').value});if(!r.ok)return alert(r.message);document.querySelector('.modal').remove();render();}
async function toggleUser(id,status){await window.api.userStatus({id:id,status:status==='ACTIVE'?'INACTIVE':'ACTIVE'});render();}
async function resetUser(id){var c=prompt('Nouveau code (minimum 4 caractères)');if(c){var r=await window.api.resetUser({id:id,code:c});if(!r.ok)alert(r.message);render();}}
function changeCode(force){document.getElementById('app').innerHTML='<div class="login"><div class="login-box"><div class="brand-big">🔐</div><h2>Changement obligatoire du code</h2><p class="muted">Définissez votre code personnel.</p><div class="field"><label>Ancien code</label><input id="oldc" type="password"></div><div class="field"><label>Nouveau code</label><input id="newc" type="password"></div><div id="msg"></div><button class="btn primary full" onclick="saveCode()">Enregistrer</button></div></div>';}
async function saveCode(){var r=await window.api.changeCode({userId:session.id,oldCode:document.getElementById('oldc').value,newCode:document.getElementById('newc').value});if(!r.ok)return document.getElementById('msg').innerHTML='<div class="error">'+esc(r.message)+'</div>';session.mustChangeCode=false;render();}
async function backup(){var r=await window.api.backup();if(r.ok)alert('Sauvegarde créée :\\n'+r.path);}
async function restore(){if(confirm('Une copie de sécurité sera créée avant restauration. Continuer ?')){var r=await window.api.restore();if(r.ok){alert('Restauration terminée.');render();}else alert(r.message||'Annulée');}}
async function showInfo(){var i=await window.api.info();alert('Base SQLite :\\n'+i.dbPath+'\\n\\nSauvegardes :\\n'+i.backupDir);}
async function reports(){return '<div class="cards">'+stat('Élèves','Exporter','students','🎓')+stat('Paiements','Exporter','payments','💰')+stat('Présences','Exporter','student_attendance','📋')+stat('Notes','Exporter','grades','📊')+'</div><div class="card"><h3>État général</h3><p>Les exports CSV sont compatibles avec Excel. Les données peuvent être imprimées depuis Windows.</p><button class="btn primary" onclick="printReport()">Imprimer</button></div>';}
async function printReport(){var d=await window.api.dashboard();var html='<html><body style="font-family:Arial;padding:30px"><h1>Ecole-App-1 — État général</h1><p>'+new Date().toLocaleString()+'</p><hr><p>Élèves : '+d.students+'</p><p>Enseignants : '+d.teachers+'</p><p>Classes : '+d.classes+'</p><p>Paiements : '+d.payments+'</p><p>Recettes : '+d.revenue+'</p><p>Présence : '+d.presenceRate+'%</p></body></html>';await window.api.print(html);}
function security(){return '<div class="card narrow"><h3>Modifier mon code</h3><div class="field"><label>Ancien code</label><input id="oldc" type="password"></div><div class="field"><label>Nouveau code</label><input id="newc" type="password"></div><button class="btn primary" onclick="saveCode()">Modifier</button></div>';}
login();